services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: easylog-python-server.api
    command:
      [
        'uv',
        'run',
        'fastapi',
        'run',
        'src/main.py',
        '--port',
        '8000',
        '--host',
        '0.0.0.0'
      ]
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped

  worker:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: easylog-python-server.worker
    command: ['uv', 'run', 'python', 'src/jobs.py']
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: easylog-python-server.nginx
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - worker
