services:
  db:
    image: postgres:16
    container_name: easylog-python-server.db
    environment:
      POSTGRES_UaSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easylog-python-server
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres_data:
