services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: easylog-python-server.api
    network_mode: 'host'
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: easylog-python-server.db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: 'host'
    ports:
      - 5432:5432
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: easylog-python-server.nginx
    network_mode: 'host'
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  postgres_data:
