[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-pagination>=0.12.32",
    "fastapi[standard]>=0.115.5",
    "openai>=1.54.4",
    "prisma>=0.15.0",
    "pydantic>=2.9.2",
]
