version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      API_ROOT_PATH: ${API_ROOT_PATH}
      API_SECRET_KEY: ${API_SECRET_KEY}
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
